# Generated by Django 3.1 on 2020-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('job_title', models.CharField(blank=True, choices=[('developer', 'Developer'), ('business_analyst', 'BA'), ('tester', 'Tester'), ('magician', 'Magic person')], max_length=30, null=True)),
            ],
        ),
    ]
